[package]
name = "caterpie"
version = "0.1.0"
edition = "2021"

[dependencies]
ash = { version = "0.38.0" }
ash-window = "0.13.0"
log = "0.4.22"
winit = { version ="0.30.8", features = ["rwh_05"]} 
env_logger = "0.11.6"
glm = "0.2.3"
